/**
 * All user-facing strings for the backend API.
 * Mirrors the frontend TEXTS pattern for consistency.
 */
export const TEXTS = {
  AUTH: {
    NOT_LOGGED_IN: '未登录，请先登录',
    TOKEN_EXPIRED: '登录已过期，请重新登录',
    NO_PERMISSION: '无权限访问',
    PERMISSION_CHECK_FAILED: '权限验证失败',
  },
  PROFILE: {
    USER_NOT_FOUND: '用户不存在',
    UPDATE_FAILED: '更新个人资料失败',
    FETCH_FAILED: '获取用户信息失败',
    INVALID_PHONE: '电话号码格式无效（请使用 E.164 格式，如 +86...）',
    NO_FIELDS_TO_UPDATE: '没有需要更新的字段',
  },
  UPLOAD: {
    INVALID_FILE_TYPE: '无效的文件类型（仅支持 JPG、PNG、WebP）',
    MISSING_EXTENSION: '缺少文件扩展名',
    URL_GENERATION_FAILED: '生成上传链接失败',
    MISSING_OBJECT_URL: '缺少文件地址',
    AVATAR_CONFIRM_FAILED: '确认头像更新失败',
  },
  PAYMENT: {
    NO_CUSTOMER: '未找到支付客户信息，请先创建订阅',
    SETUP_INTENT_FAILED: '创建支付设置失败',
    LIST_FAILED: '获取支付方式列表失败',
    SET_DEFAULT_FAILED: '设置默认支付方式失败',
    DELETE_FAILED: '删除支付方式失败',
    NOT_FOUND: '支付方式不存在',
    DELETE_CONFIRM: '支付方式已删除',
    DEFAULT_SET: '已设为默认支付方式',
  },
  CONTENT: {
    NOT_FOUND: '内容不存在',
    IMPORT_FAILED: '导入内容失败',
    IMPORT_STARTED: '导入已开始',
    URL_REQUIRED: '请提供文章URL',
    INVALID_URL: '无效的URL格式',
    PIPELINE_FAILED: 'AI处理失败',
    ALREADY_PROCESSING: '该内容正在处理中',
    PUBLISH_SUCCESS: '内容已发布',
    ARCHIVE_SUCCESS: '内容已归档',
    DELETE_SUCCESS: '内容已删除',
    QUIZ_SUBMIT_SUCCESS: '测验提交成功',
    WORD_SAVED: '单词已保存到SRS',
    PROGRESS_UPDATED: '阅读进度已更新',
  },
  TOPIC: {
    NOT_FOUND: '话题不存在',
    NAME_REQUIRED: '话题名称不能为空',
    ALREADY_EXISTS: '话题已存在',
    CREATE_SUCCESS: '话题创建成功',
    UPDATE_SUCCESS: '话题更新成功',
  },
  LISTENING: {
    NOT_FOUND: '听力内容不存在',
    TITLE_REQUIRED: '请提供标题',
    TRANSCRIPT_REQUIRED: '请提供文字转录',
    CREATE_SUCCESS: '听力内容创建成功',
    UPLOAD_URL_GENERATED: '上传链接已生成',
    UPLOAD_FINALIZED: '音频上传已确认',
    PIPELINE_STARTED: 'AI处理已开始',
    PIPELINE_FAILED: 'AI处理失败',
    PUBLISH_SUCCESS: '听力内容已发布',
    ARCHIVE_SUCCESS: '听力内容已归档',
    QUIZ_SUBMIT_SUCCESS: '听力测验提交成功',
    PROGRESS_UPDATED: '收听进度已更新',
    NO_QUIZ: '暂无听力测验题目',
    AUDIO_URL_REQUIRED: '外部音频地址不能为空',
    SOURCE_TYPE_REQUIRED: '请提供来源类型（UPLOAD 或 URL）',
  },
  READINESS: {
    FETCH_FAILED: '获取JLPT准备度失败',
  },
  SENTENCES: {
    GENERATE_FAILED: '生成例句失败',
    BATCH_LIMIT: '每次最多生成10个词的例句',
  },
  COURSE: {
    NOT_FOUND: '课程不存在',
    CREATE_SUCCESS: '课程创建成功',
    UPDATE_SUCCESS: '课程更新成功',
    DELETE_SUCCESS: '课程删除成功',
    PUBLISH_SUCCESS: '课程已发布',
    UNPUBLISH_SUCCESS: '课程已取消发布',
    HAS_PROGRESS: '该课程已有学习进度，无法删除',
    LESSON_NOT_FOUND: '课时不存在',
    LESSON_CREATE_SUCCESS: '课时创建成功',
    LESSON_UPDATE_SUCCESS: '课时更新成功',
    LESSON_DELETE_SUCCESS: '课时删除成功',
    LESSON_NUMBER_CONFLICT: '课时编号已存在',
    REORDER_SUCCESS: '课时排序更新成功',
    VALIDATION_FAILED: '输入验证失败',
  },
  GRAMMAR_MATCH: {
    NO_TOKENS: '请提供Token数据',
    TOO_MANY_TOKENS: 'Token数量超过上限',
    INVALID_TOKEN_FORMAT: 'Token格式无效',
    MATCH_SUCCESS: '语法模式匹配完成',
    MATCH_FAILED: '语法模式匹配失败',
  },
} as const;
